### ISSUE TITLE
About differential expression analysis using pseudobulk method (utilizing dreamlet package)

### ISSUE THREAD

**Issue by RJ-Lupin** [YosefLab/CZI-Immuneaging#95]
Hello,

I am truly impressed by your work.
I am deeply interested in your research and eager to apply both the data and analytical methods to my own studies. However, I have a question regarding the differential expression analysis, particularly the part utilizing the dreamlet package in your paper.
In your source code, you employed the dreamlet package and included an intercept of 0 in the formula. However, I am not very familiar with the linear mixed model used to estimate the DEGs. Hence, I would like to inquire whether it is appropriate to include the intercept 0 in my case. Could you please review my experimental design and confirm whether the formula is correctly formulated?
My data is structured as follows: I have two groups of data. The control group comprises 5 individuals, while the therapy-treated group comprises 7 individuals. My objective is to identify cell-type-specific DEGs between these two groups while accounting for individual variability as a random effect.

Which formula is more suitable for my case?
1.	form <- ~ treatment_group + (1|individual)
2.	form <- ~ treatment_group + (1|individual) + 0

I am only considering the individual as a random effect at the moment, without taking into account other potential confounding factors.

Thank you for your guidance and expertise.

**Comment by canergen** [comment]
In our case we use the intercept so that no reference group is used but for every covariate we estimate an effect. This makes the formula easier. If you have a one-vs-one comparison (sounds like). It's perfectly fine to usually set the control group as the reference and remove the intercept. However, for user questions to dreamlet please consider asking questions in their GitHub repository. Closing here.
